### ISSUE TITLE
Auswahl Übertragungsprotokoll der Messwerte

### ISSUE THREAD

**Issue by Hofei90** [Hofei90/Lux_UV_Sensorprojekt#5]
Geklärt werden muss noch den Übertragungsweg der Messwerte von ESP zum Raspberry Pi, welcher die Messwerte entgegennimmt und weiterverarbeitet (Eintragung in WeeWx Datenbank und oder Übertragung an Grafana Server zur visualisierung).

2 Möglichkeiten welche ich aktuell in Betracht ziehe:
- Übertragung mittels MQTT, Nachteil ist es wird eine weitere Software am Raspberry Pi nötig.

- Mit einem Pythonskript ein Socket öffnen und so die Daten entgegennehmen.

Beide Möglichkeiten funktionieren (bewusst) ohne weitere Maßnahmen nur im lokalen Netzwerk.
Der ESP wird nach der Messung in den Tiefschlaf geschickt um Strom zu sparen, er kann somit nicht als Webserver funktionieren wo die Messwerte selbst abgeholt werden, sondern muss diese aktiv an den Raspberry Pi nach erfolgreicher Messung schicken.

Weitere Vorschläge?

**Comment by linusg** [comment]
> Beide Möglichkeiten funktionieren (bewusst) ohne weitere Maßnahmen nur im lokalen Netzwerk.

Wie meinst du das?

> Weitere Vorschläge?

Technisch gesehen auch nur ein Socket, aber mit HTTP bekommst du ein fertiges Protokoll, dann ist eben nicht der ESP Webserver sondern schickt POST-Requests. Über Vor/Nachteile bei jeweils HTTP und MQTT könnte man streiten.

**Comment by Hofei90** [comment]
> Wie meinst du das?

Gemeint ist, dass ohne Portöffnung im Router oder Erstellung eines VPN Tunnels nur innerhalb des lokalen Netzwerkes die Daten ausgetauscht werden können￼

> Technisch gesehen auch nur ein Socket, aber mit HTTP bekommst du ein fertiges Protokoll, dann ist eben nicht der ESP Webserver sondern schickt POST-Requests. Über Vor/Nachteile bei jeweils HTTP und MQTT könnte man streiten.

Du meinst also, dass der Pi Beispielsweise mit Flask Einen Server bereitstellt und hier rüber die Post requests entgegen nimmt?￼

**Comment by linusg** [comment]
> Gemeint ist, dass ohne Portöffnung im Router oder Erstellung eines VPN Tunnels nur innerhalb des lokalen Netzwerkes die Daten ausgetauscht werden können

Das stimmt aber nicht - wieso sollte das nicht gehen? Was spricht dagegen, eine aus dem Internet erreichbare IP-Adresse/Domainnamen einzustellen, die der ESP dann anspricht?

> Du meinst also, dass der Pi Beispielsweise mit Flask Einen Server bereitstellt und hier rüber die Post requests entgegen nimmt?￼

Ja, zum Beispiel.

**Comment by Hofei90** [comment]
> Das stimmt aber nicht - wieso sollte das nicht gehen?

Bezogen natürlich darauf, dass der Pi sich ebenfalls in dem lokalen Netzwerk befindet. Schlecht formuliert sry

**Comment by Hofei90** [comment]
Die Entscheidung fiel auf MQTT.
Zum einen, wollte ich es einfach mal ausprobieren. Außerdem entdeckte ich eine nützliches Addon in Homematic Namens Redmatic mit dem ich spielend leicht meine aktuelle Werte per MQTT zur Verfügung stellen kann.
